### ISSUE TITLE
The character can jump more than twice in a row

### ISSUE THREAD

**Issue by MarkfuGod** [MarkfuGod/Commissaire#2]
When 'w' is pressed, the movement of the character is 'jump'.
*TODO:* We need the character to jump no more than twice in a row.
*Idea:*  
1. Initialize a function called 'jumping' to false.
```javascript
let jumping = false;
```
2. When the player presses the jump button (e.g., 'W' key), check if they are already jumping. If not, set `jumping` to true and apply the necessary physics for the player to jump.
```javascript
if (!jumping) {
// Apply jump physics here
jumping = true;
}
```
3. In the update loop, check if the player is still jumping. If they are, apply additional physics to make them jump again (e.g., add another burst of upward momentum).
```javascript
if (jumping) {
// Apply second jump physics here
jumping = false;}
```
4. Set a cooldown period between jumps. This means that after the player has jumped twice, they won't be able to jump again for a certain amount of time (e.g., 0.5 seconds).
```javascript
let jumpCooldown = 0.5;// In the update loop
if (jumping || (time - jumpCooldown > 0)) {
// Apply jump physics here
jumping = true;}
```
5. This way, the player will be able to jump once, then jump again after a short cooldown period, but they won't be able to jump continuously without landing in between. Adjust the cooldown period as needed to achieve the desired gameplay feel.

**Comment by APeng215** [comment]
What if the `jumpCooldown` resets ***before*** the player landing on ground? Will the player be able to apply jumping at this point?
