### ISSUE TITLE
Designing map for Phase 2

### ISSUE THREAD

**Issue by MarkfuGod** [MarkfuGod/Commissaire#7]
<img width="877" alt="截屏2023-11-20 14 50 26" src="https://github.com/MarkfuGod/Commissaire/assets/102947436/62304801-a579-4430-bfb1-7f25f1fbf3fa">

**I'm currently designing the map for level 2, guys, give me some ideas or inspirations plz**
*Map Source: https://brullov.itch.io/oak-woods/devlog/112437/oak-woods-environment-asset-v10-released*

**Comment by MarkfuGod** [comment]
*Map psd file* : https://www.dropbox.com/scl/fi/ei58ie9gqcqrhv5kw6q0n/SP-Commissaire.zip?rlkey=4yls32z0tjg4xdtyal2ombhul&dl=0

**Comment by MarkfuGod** [comment]
*Map psd file* : https://www.dropbox.com/scl/fi/ei58ie9gqcqrhv5kw6q0n/SP-Commissaire.zip?rlkey=4yls32z0tjg4xdtyal2ombhul&dl=0

**Comment by APeng215** [comment]
Article about entity AI in MC: https://www.mcbbs.net/thread-1285618-1-1.html

**Comment by MarkfuGod** [comment]
C:\Users\DELL\Documents\GitHub\Commissaire\assets\img\background.png

**Comment by MarkfuGod** [comment]
![background](https://github.com/MarkfuGod/Commissaire/assets/102947436/459cbb77-ec57-40f9-aa73-59adf9bc1384)

**Comment by MarkfuGod** [comment]
*Done*
