### ISSUE TITLE
Game speed is bound to the display rate

### ISSUE THREAD

**Issue by APeng215** [MarkfuGod/Commissaire#8]
## Here's a bug

Game speed is bound to the display rate. On high display rate screen (like 144Hz), the game speed will be very fast, including the running speed of the player, attake speeding and so on.

## Reason

*The `window.requestAnimationFrame()` method tells the browser that you wish to perform an animation. It requests the browser to call a user-supplied callback function prior to the next repaint.*
****The frequency of calls to the callback function will generally match the display refresh rate.*** The most common refresh rate is 60hz, (60 cycles/frames per second), though 75hz, 120hz, and 144hz are also widely used.*
See in: https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame

**Comment by MarkfuGod** [comment]
👍 Good job ❤️

**Comment by MarkfuGod** [comment]
🔨 I'll look into it
